# LOCAL FILES AND FOLDERS
LOC_DIR: '/home/demuzmp4/Nextcloud/data/wudapt/dynamic-lcz'
GF_FOLDER: 'dynamic-lcz'

# EE dir for training areas
EE_DIR: 'projects/WUDAPT/LCZ_L0/dynamic-lcz'
EE_SET_ACCOUNT: "/home/demuzmp4/Nextcloud/scripts/tools/set_ee_account.sh"

# Image collection settings
CC: 70
EXTRA_DAYS: 90

# LCZ mapping parameters
lcz:
  ROIBUFFER: 15000
  SCALE: 30
  POLYSIZE: 300000
  NRLCZ: 17
  RFNRTREES: 30
  NRBOOT: 25
  BOOTTRESH: 0.7
  BUFFERSIZE: 300
  BANDS: [ "blue", "green", "red", "nir", "swir1", "swir2", "tirs1",
           "bci", "ndbai", "ndwi_max", "ndvi_min", "ndvi_max", "slope" ]
  BANDS_FLY: ['blue', 'green', 'red', 'nir', 'swir1', 'tirs1', 'swir2']
  COLORS: [
      '#8C0000', '#D10000', '#FF0000', '#BF4D00',
      '#FF6600', '#FF9955', '#FAEE05', '#BCBCBC',
      '#FFCCAA', '#555555', '#006A00', '#00AA00',
      '#648525', '#B9DB79', '#000000', '#FBF7AE',
      '#6A6AFF',
  ]

# Other
CM_WEIGHTS: './tables/LCZ_metric.csv'

Hyderabad:
  TA: ["[Hyderbad_2003][16-06-2021][Siva Ram Edupuganti_Mahua Mukherjee].kml",
       "[Hyderbad_2015][16-06-2021][Siva Ram Edupuganti_Mahua Mukherjee].kml",
       "[Hyderbad_2017][25-06-2021][Siva Ram Edupuganti_Mahua Mukherjee].kml",
       "[Hyderbad_2019][16-06-2021][Siva Ram Edupuganti_Mahua Mukherjee].kml",
      ]
