TA:
  v1:
    2006: "[Melbourne][2006][JamesBennie].kmz"
    2016: "[Melbourne][2016][JamesBennie].kmz"
    2019: "[Melbourne][2019][JamesBennie].kml"

AUTHOR: "James Bennie"

# Image collection settings
CC: 70
EXTRA_DAYS: 180
ADD_L7: "True"
JD_START: 0
JD_END: 366

# ASSET INFO
EXPORT_TO_ASSET: "False"
EE_IN_DIR: "projects/ee-mdemuzere/assets/multitemp-lcz"
EXPORT_SCALE: 30

# LCZ mapping parameters
LCZ:
  ROIBUFFER: 15000
  SCALE: 100
  POLYSIZE: 300000
  NRLCZ: 17
  RFNRTREES: 30
  NRBOOT: 25
  BOOTTRESH: 0.7
  BUFFERSIZE: 300
  COLORS: [
      '#8C0000', '#D10000', '#FF0000', '#BF4D00',
      '#FF6600', '#FF9955', '#FAEE05', '#BCBCBC',
      '#FFCCAA', '#555555', '#006A00', '#00AA00',
      '#648525', '#B9DB79', '#000000', '#FBF7AE',
      '#6A6AFF',
  ]

# Confusion Matrix weights
CM_WEIGHTS: './tables/LCZ_metric.csv'

# Folder on your google drive
GD_FOLDER: "EE"


